# from database.db_config import get_connection
# from core.account import Account

# class AccountRepo:
#     @staticmethod
#     def create_account(account: Account):
#         conn = get_connection()
#         cursor = conn.cursor()
#         sql = """INSERT INTO accounts (title, cell, acc_type, unit, address, status)
#                  VALUES (%s, %s, %s, %s, %s, %s)"""
#         values = (account.title, account.cell, account.acc_type,
#                   account.unit, account.address, account.status)
#         cursor.execute(sql, values)
#         conn.commit()
#         acc_id = cursor.lastrowid
#         cursor.close()
#         conn.close()
#         return acc_id

#     @staticmethod
#     def update_account(account: Account):
#         conn = get_connection()
#         cursor = conn.cursor()
#         sql = """UPDATE accounts 
#                  SET title=%s, cell=%s, acc_type=%s, unit=%s, address=%s, status=%s
#                  WHERE acc_id=%s"""
#         values = (account.title, account.cell, account.acc_type,
#                   account.unit, account.address, account.status, account.acc_id)
#         cursor.execute(sql, values)
#         conn.commit()
#         cursor.close()
#         conn.close()

    
#     @staticmethod
#     def get_all_accounts():
#         conn = get_connection()
#         cursor = conn.cursor(dictionary=True)
#         cursor.execute("SELECT * FROM accounts ORDER BY acc_id ASC")
#         result = cursor.fetchall()
#         cursor.close()
#         conn.close()
#         return result

#     @staticmethod
#     def get_active_accounts():
#         conn = get_connection()
#         cursor = conn.cursor(dictionary=True)
#         cursor.execute("SELECT * FROM accounts WHERE status='active'")
#         result = cursor.fetchall()
#         cursor.close()
#         conn.close()
#         return result

#     @staticmethod
#     def get_inactive_accounts():
#         conn = get_connection()
#         cursor = conn.cursor(dictionary=True)
#         cursor.execute("SELECT * FROM accounts WHERE status='inactive'")
#         result = cursor.fetchall()
#         cursor.close()
#         conn.close()
#         return result

#     @staticmethod
#     def get_account_by_id(acc_id: int):
#         conn = get_connection()
#         cursor = conn.cursor(dictionary=True)
#         cursor.execute("SELECT * FROM accounts WHERE acc_id=%s", (acc_id,))
#         account = cursor.fetchone()
#         cursor.close()
#         conn.close()
#         return account


#     # ✅ NEW: Check if account exists (for validation before update/delete)
#     @staticmethod
#     def account_exists(acc_id: int) -> bool:
#         conn = get_connection()
#         cursor = conn.cursor()
#         cursor.execute("SELECT COUNT(*) FROM accounts WHERE acc_id=%s", (acc_id,))
#         (count,) = cursor.fetchone()
#         cursor.close()
#         conn.close()
#         return count > 0

#     @staticmethod
#     def get_next_acc_id():
#         """Get the next available account ID (max+1)."""
#         conn = get_connection()
#         cursor = conn.cursor(dictionary=True)
#         cursor.execute("SELECT MAX(acc_id) AS max_id FROM accounts")
#         row = cursor.fetchone()
#         cursor.close()
#         conn.close()
#         return (row["max_id"] or 0) + 1


#     @staticmethod
#     def search_accounts(query):
#         conn = get_connection()
#         cursor = conn.cursor(dictionary=True)

#         if not query:  # if query is empty, return all accounts
#             cursor.execute("SELECT * FROM accounts")
#             results = cursor.fetchall()
#         else:
#             pattern = f"%{query}%"
#             sql = """
#             SELECT * FROM accounts
#             WHERE acc_id LIKE %s
#             OR title LIKE %s
#             OR acc_type LIKE %s
#             OR unit LIKE %s
#             OR address LIKE %s
#             OR status LIKE %s
#             """
#             cursor.execute(sql, (pattern, pattern, pattern, pattern, pattern, pattern))
#             results = cursor.fetchall()

#         cursor.close()
#         conn.close()
#         return results




# database/account_repo.py


from core.account import Account
from database.db_config import get_connection  # your DB connection helper

class AccountRepo:

    @staticmethod
    def add_account(account: Account):
        """
        Adds a new account to the DB. account_code is auto-generated by DB trigger.
        """
        conn = get_connection()
        cursor = conn.cursor()
        query = """
        INSERT INTO accounts (title, account_type, unit, cell)
        VALUES (%s, %s, %s, %s)
        """
        cursor.execute(query, (account.title, account.account_type, account.unit, account.cell))
        conn.commit()
        account.acc_id = cursor.lastrowid

        # Fetch the generated account_code
        cursor.execute("SELECT account_code FROM accounts WHERE acc_id = %s", (account.acc_id,))
        account.account_code = cursor.fetchone()[0]

        cursor.close()
        conn.close()
        return account

    @staticmethod
    def get_account_by_code(account_code):
        conn = get_connection()
        cursor = conn.cursor(dictionary=True)
        cursor.execute("SELECT * FROM accounts WHERE account_code=%s", (account_code,))
        row = cursor.fetchone()
        cursor.close()
        conn.close()
        if row:
            return Account(**row)
        return None

    @staticmethod
    def update_account(account: Account):
        """
        Updates account details (title, unit, cell, status)
        """
        conn = get_connection()
        cursor = conn.cursor()
        query = """
        UPDATE accounts
        SET title=%s, unit=%s, cell=%s, status=%s
        WHERE account_code=%s
        """
        cursor.execute(query, (account.title, account.unit, account.cell, account.status, account.account_code))
        conn.commit()
        cursor.close()
        conn.close()
        return account

    @staticmethod
    def list_accounts(account_type=None):
        """
        Lists all accounts or filters by type
        """
        conn = get_connection()
        cursor = conn.cursor(dictionary=True)
        if account_type:
            cursor.execute("SELECT * FROM accounts WHERE account_type=%s", (account_type,))
        else:
            cursor.execute("SELECT * FROM accounts")
        rows = cursor.fetchall()
        cursor.close()
        conn.close()
        return [Account(**row) for row in rows]

    @staticmethod
    def deactivate_account(account_code):
        """
        Soft-delete an account by setting status to INACTIVE
        """
        conn = get_connection()
        cursor = conn.cursor()
        cursor.execute("UPDATE accounts SET status='INACTIVE'  WHERE account_code=%s", (account_code,))
        conn.commit()
        cursor.close()
        conn.close()

    @staticmethod
    def get_account_by_code(account_code):
        conn = get_connection()
        cursor = conn.cursor(dictionary=True)
        query = "SELECT * FROM accounts WHERE account_code = %s"
        cursor.execute(query, (account_code,))
        row = cursor.fetchone()
        cursor.close()
        conn.close()
        if row:
            
            return Account(
                account_code=row["account_code"],
                title=row["title"],
                account_type=row["account_type"],
                unit=row.get("unit"),
                cell=row.get("cell"),
                status=row.get("status")
            )
        return None




